# Generated by Django 5.2.1 on 2025-05-22 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_receipt_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='description',
        ),
        migrations.AddField(
            model_name='receipt',
            name='added_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cook_time',
            field=models.CharField(max_length=10),
        ),
    ]
