# Generated by Django 5.2.1 on 2025-05-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_receipt_description_receipt_added_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='Recipe',
        ),
    ]
